source $__env/vim/modules/defs_default.vim 
source $__env/vim/modules/plug_main.vim
source $__env/vim/modules/plug_fzf.vim
source $__env/vim/modules/plug_autosave.vim
source $__env/vim/modules/plug_lsp.vim
