source $__configs/vim/modules/settings.vim " (Vundle, Vim-Plug)
source $__configs/vim/modules/keyboard.vim
source $__configs/vim/modules/plugins.vim

set t_Co=256
colorscheme 1989
colorscheme gruvbox
